apiVersion: v1
kind: Service
metadata:
  name: rollout-bluegreen-active
spec:
  type: NodePort
  selector:
    app: demo-rollout
  ports:
      - nodePort: 31005
        protocol: TCP
        port: 8080
